### ISSUE TITLE
Should exit if `--input-file` replayed all requests

### ISSUE THREAD

**Issue by buger** [buger/goreplay#456]
Right now it just hangs and does nothing.

**Comment by klivan** [comment]
+1
For now I'm using hack like this (I have only 1 input file) but would love to have this feature in gor:
```bash
#!/bin/bash

INPUTFILE="input.gor"
LOGFILE="/tmp/gor.log"
MATCH="FileInput: end of file"

gor --input-file "$filename" --output-http="http://www.test.com" 2>&1 | tee $LOGFILE &
while sleep 5
do
    if fgrep --quiet "$MATCH" "$LOGFILE"
    then
        exit 0
    fi
done
```

**Comment by klivan** [comment]
@buger I see this was closed. So it won't be included in the next release?

**Comment by buger** [comment]
Sorry for the confusion. It is fixed in upcoming 0.16.1 which will be release today. I will notify you here :)

**Comment by im-bart** [comment]
This issue is not fixed, it'll still hang on --file-input. OS X binary, version 0.16.1.

**Comment by buger** [comment]
I really look like a lock somewhere in --input-file, can't find it yet 😭

**Comment by jordangarrison** [comment]
Hello @buger,

I think this may still be an issue. I'm using a similar workaround to the one shown above.

 I'm running version 1.2.0. Love the project!

**Comment by urbanishimwe** [comment]
Verified too on my end, this should be tracked on a separate issue.
