### ISSUE TITLE
Goreplay omits 3 monkeys separator between requests

### ISSUE THREAD

**Issue by orZeira** [buger/goreplay#897]
Hi,
I'm working with gor-1.2.0 on ubuntu 16.04.

It seems that gor doesn't separate requests with the 3 monkeys separator once in a while when writing to file, this results in corrupted requests when trying to replay those files later.

I was able to see that problem occurs with http requests with content length of around ~15kb.
I thought that maybe the problem was an overload of requests but using rate limit of 10 rps didn't solve that either.

e.g. for missing separator:
`1 d5990a95eb21e2450420eabb08977847bc1c1c6f 1612344573714086685 1765207038
POST /auctions HTTP/1.1
host: some_host.com
Accept-Encoding: gzip
Content-Type: application/json; charset=UTF-8
X-OpenRTB-Version: 2.5
X-Forwarded-For: some_ip
X-Forwarded-Port: 80
X-Forwarded-Proto: http
Content-Length: 20710
Connection: keep-alive

{body...}POST /auctions HTTP/1.1
host: some_host.com
Accept-Encoding: gzip
Content-Type: application/json; charset=UTF-8
X-OpenRTB-Version: 2.5
X-Forwarded-For: some_ip
X-Forwarded-Port: 80
X-Forwarded-Proto: http
Content-Length: 2543
Connection: keep-alive

{body...}`

Any ideas?

**Comment by urbanishimwe** [comment]
the same issue was fixed some time ago! you may consider using the latest version!

**Comment by orZeira** [comment]
Hi, thanks for the quick response.

Just tried to use gor v1.3.0_RC1 (latest version) and the problem still occurs...

**Comment by 15927017493** [comment]
I was in the same situation when i tried to use gor v1.3.0_RC1 (latest version)

**Comment by 15927017493** [comment]
🐵🙈🙉
1 97f24f691679ae39af869b66 1619517103027365155 770242115
POST /cart/web/guide HTTP/1.1
Host: 
X-Real-IP: 
X-Forwarded-For: 
X-Forwarded-Proto: 
X-Forwarded-Port: 
X-Forwarded-Host: 
Content-Length: 87
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Accept: text/plain, */*; q=0.01
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: https://xxxxxxxxxxxxxxxxxxxxxxxx
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://xxxxxxxxxxxxxxx
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: gr_user_id=accc91c0-c63f-4c61-9248-91d1a474216c; grwng_uid=6872baec-9f34-46d0-b9bd-b73f93f4b61b; \143\150\145\143\153\123\145\164\164\154\145\151\156=\164\162\165\145; WSESSIONID=7aa40a7f-1dbd-44cb-9122-f14c76e527d7; 9d2350559e69271a_gr_session_id=03eb682b-a116-4078-9693-02df4f1c3788; PSESSIONID=1552fac2-a497-43e7-a071-e229c4fa21ad; ssoAuthCode=qbTQPq; security_context=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXNzbWFsbC5jb20iLCJzdWIiOiJsZHhteSIsImdyb3VwVXNlciI6ImZhbHNlIiwicmVwcmVzZW50YXRpdmVDb21wYW55SWQiOiIxMjI3MiIsInJlZ2lzdGVyQ29tcGxldGVkIjoidHJ1ZSIsImNvbXBhbnlUeXBlIjoiR0FSQUdFIiwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjoidHJ1ZSIsImFkZGl0aW9uYWxJbmZvIjoie2FjY291bnRJZD01ZjExODA0YzRlNjk3MTAwMDEzNzIwZTV9IiwiYWNjb3VudE5vbkV4cGlyZWQiOiJ0cnGET /webim/im/conversation?userId=ldxmy&unread=true&tenantId=CASS_EC&_=1619517103776 HTTP/1.1
Host: 
X-Real-IP: 
X-Forwarded-For: 
X-Forwarded-Proto: 
X-Forwarded-Port: 
X-Forwarded-Host: 
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
Accept: */*
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://XXXXXX
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: gr_user_id=accc91c0-c63f-4c61-9248-91d1a474216c; grwng_uid=6872baec-9f34-46d0-b9bd-b73f93f4b61b; \143\150\145\143\153\123\145\164\164\154\145\151\156=\164\162\165\145; WSESSIONID=7aa40a7f-1dbd-44cb-9122-f14c76e527d7; 9d2350559e69271a_gr_session_id=03eb682b-a116-4078-9693-02df4f1c3788; PSESSIONID=1552fac2-a497-43e7-a071-e229c4fa21ad; ssoAuthCode=qbTQPq; security_context=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXNzbWFsbC5jb20iLCJzdWIiOiJsZHhteSIsImdyb3VwVXNlciI6ImZhbHNlIiwicmVwcmVzZW50YXRpdmVDb21wYW55SWQiOiIxMjI3MiIsInJlZ2lzdGVyQ29tcGxldGVkIjoidHJ1ZSIsImNvbXBhbnlUeXBlIjoiR0FSQUdFIiwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjoidHJ1ZSIsImFkZGl0aW9uYWxJbmZvIjoie2FjY291bnRJZD01ZjExODA0YzRlNjk3MTAwMDEzNzIwZTV9IiwiYWNjb3VudE5vbkV4cGlyZWQiOiJ0cnVlIiwiZW5hYmxlZCI6InRydWUiLCJ1c2VybmFtZSI6ImxkeG15IiwiYWNjb3VudE5vbkxvY2tlZCI6
🐵🙈🙉
